### ISSUE TITLE
linter doesn't mark missing "joker" symbols when the dialect isn't joker

### ISSUE THREAD

**Issue by nicwest** [candid82/joker#33]
I'm not sure if this expected behaviour but when I have a clojure file like this:

```clj
;foo.clj
(ns foobar.core)

(joker.string/split "ha-ha-ha-ha" #"-")
```

and I run the linter I get no errors:

```bash
$ joker --lint foo.clj
$ joker --lintclj foo.clj
```

If I introduce an error by removing the pattern from the original example:

```clj
;foo.clj
(ns foobar.core)

(joker.string/split "ha-ha-ha-ha")
```
you get joker errors

```bash
$ joker --lint foo.clj
foo.clj:4:1: Parse warning: Wrong number of args (1) passed to #'joker.string/split
$ joker --lintclj foo.clj
foo.clj:4:1: Parse warning: Wrong number of args (1) passed to #'joker.string/split
```

I'm expecting something along the lines of this when I lint this clojure file as the joker dialect:

```clj
;foo.clj
(ns foo.core)

(clojure.string/split "ha-ha-ha-ha" #"-")
```

```bash
$ joker --lintjoker input.clj
input.clj:4:2: Parse error: Unable to resolve symbol: clojure.string/split
```

**Comment by candid82** [comment]
This is a known issue: joker loads its standard namespaces (`joker.string`, `joker.os` etc) no matter what dialect is used for linting. Should not be a problem in practice, but I'll see if this can be cleaned up...

**Comment by candid82** [comment]
This should be fixed by https://github.com/candid82/joker/commit/4f8804e392c4486c2ab6bc26ae8595217fe265b8

**Comment by borkdude** [comment]
Still seeing this with v0.8.7.
<img width="461" alt="screenshot 2017-12-21 16 55 30" src="https://user-images.githubusercontent.com/284934/34263433-cf443018-e66f-11e7-8a8a-6bdec8b25fff.png">

**Comment by candid82** [comment]
Are you referring to the fact that it says "joker.core" instead of "clojure.core"? The warning itself is legit (assoc-in only takes 3 arguments), so this looks like a cosmetic issue that has been there from the very beginning.

**Comment by borkdude** [comment]
Sorry, I thought the issue was about that.
